version: "3"  # changed from 2.1 to 3 (latest version)
services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: hanbrake
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /E/DockerContainers/HandBrake/appdata:/config:rw \
      - /E/DockerContainers/HandBrake/user:/storage:ro \
      - /E/DockerContainers/HandBrake/watch:/watch:rw \
      - /E/DockerContainers/HandBrake/output:/output:rw \
    ports:
      - 5800:5800
    restart: unless-stopped