services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /G/Archive/Media/nextcloud/config:/config
      - /G/Archive/Media/nextcloud/data:/data
    ports:
      - 4500:80
      - 443:443
    restart: unless-stopped

