---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /G/Archive/Media/radarr/data:/config
      - /G/Archive/Media/radarr/movies:/movies #optional
      - /G/Archive/Media/radarr/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
