version: "3"  # changed from 2.1 to 3 (latest version)
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jelly
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /E/Media/jelly/library:/config
      - /E/Media/TV/Comedy:/data/TV/Comedy
      - /E/Media/TV/Crime:/data/TV/Crime
      - /E/Media/Movie/Comedy:/data/Movies/Comedy
      - /E/Media/Movie/Crime:/data/Movies/Crime
      - /E/Media/TV/SciFi:/data/TV/SciFi
      - /E/Media/Movie/SciFi:/data/Movies/SciFi
    #  - /E/Media/Movies-SciFi:/data/Movies-SciFi
    #  - /E/Media/Documentaries1:/data/docu
    #  - /E/Media/Kids:/data/kids movies
      - /persistent-storage:/var/lib/jellyfin  # added for persistent storage
    ports:
      - 8096:8096
    restart: unless-stopped
