version: "3"  # changed from 2.1 to 3 (latest version)
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jelly
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /E/Media/jelly/library:/config
      - /E/Media/TV-Comedy:/data/Comedy
      - /E/Media/TV-Crime:/data/Crime
      - /E/Media/TV-Horror:/data/Horror
      - /E/Media/TV-SciFi:/data/SciFi
      - /E/Media/Movies-SciFi:/data/Movies-SciFi
    #  - /E/Media/Documentaries1:/data/docu
      - /E/Media/Kids:/data/kids movies
      - /persistent-storage:/var/lib/jellyfin  # added for persistent storage
    ports:
      - 8096:8096
    restart: unless-stopped
