---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/London
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - C:\Users\keith\Downloads\KLTECHVIDEOS\Jellyseerr\config:/app/config
    restart: unless-stopped
